### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by Jador** [hypeserver/react-date-range#24]
Might be a good idea to add some unit testing.

@burakcan any preference on framework?

**Comment by burakcan** [comment]
Yup, this might be really useful. Currently i don't have any strong preference on framework but i think we should discuss to select one.

@fatiherikli @strada @gurel

**Comment by usirin** [comment]
I think `mocha` and `mjackson/expect`, or `jest` are the 2 options that is very common in react community.

**Comment by redaxmedia** [comment]
Just use Jasmine as it contains code coverage features too. Otherwise you need something like blanket.js while using mocha. AVA is also another option.
