### ISSUE TITLE
wrong dateRange on hover

### ISSUE THREAD

**Issue by ayxos** [hypeserver/react-date-range#368]
## Subject of the issue
Latest version selects the wrong dateRange on hover
 
## [BUG] Bug Reproduce Steps
https://adphorus.github.io/react-date-range/
hover on "this week" or any other option, the whole month is preselected, but on click works fine.

## [BUG] Expected behaviour
hover on "this week" should mark the current week.

## Environment
Package Version: "^1.0.3"
React version: n/a
Node version: n/a
Browser: Chrome

**Comment by Grawl** [comment]
I can confirm that this issue exist.

Even can't hide preview range (as a rowkaround) with CSS because `.rdrDayInPreview` used for hovering a day __and__ highlighting of a day for range preview.

**Comment by lysoff** [comment]
is there any progress here? looks like a quick fix

**Comment by Ensaphelon** [comment]
Facing the same issue

**Comment by lucyyu24** [comment]
same here! any progress on this?

**Comment by chrisclausen90** [comment]
Solved with latest version update
