### ISSUE TITLE
Accessibility Issues with the arrows buttons 

### ISSUE THREAD

**Issue by VRedondo** [hypeserver/react-date-range#373]
## Subject of the issue
Arrow buttons do not pass ARIA Test
 
## [BUG] Bug Reproduce Steps
1. Install the next add on for web accessibility testing 
https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd
2. Ran the test with the range picker open
3. The plugin reports issues with the arrow buttons at the top of the picker, indicating that these do not have a discernible text
https://dequeuniversity.com/rules/axe/3.5/button-name?application=AxeChrome

## [BUG] Expected behaviour
The react-date-range picker should include in their API a way to set a aria-label to these buttons

## Environment
Package Version: 1.0.3
React version: 16.12.0
Node version: n/a
Browser: Version 81.0.4044.138 (Official Build) (64-bit)
<img width="922" alt="Screenshot at May 22 15-15-50" src="https://user-images.githubusercontent.com/6404673/82710050-2e302000-9c3f-11ea-8977-49b4edce6f20.png">

**Comment by kamyar** [comment]
Should be fixed please feel free to open a new issue if something is missing
