### ISSUE TITLE
"Center" calendar view

### ISSUE THREAD

**Issue by apucacao** [hypeserver/react-date-range#39]
Hi there,

Thanks for this great component! Installed it yesterday, and fit right in.

One thing I noticed was that when selecting a date range via the presets, the calendars might become out of sync. That is, the start date might actually be out of bounds of the left calendar. Is there a way to make sure both the start and end dates are always visible?

Thanks,

Alexis

**Comment by burakcan** [comment]
thank you @apucacao :+1: . I'll try to figure it out

**Comment by jaimz22** [comment]
I was just coming to make this suggestion. is this going to happen at all?
