### ISSUE TITLE
Add time selector

### ISSUE THREAD

**Issue by eskimoblood** [hypeserver/react-date-range#4]
Would be nice if the widget would also have selectors for `hours` and `minutes`.

**Comment by burakcan** [comment]
Thank you for the suggestion @eskimoblood .
It's on my plans but i'm currently deferring it. Because the initial idea was built around 'dates' and current feature set (dates) is not complete yet.

ps: if someone have time... :+1:  :)

**Comment by leesalminen** [comment]
My team may be tackling this next week. Stay tuned! We'd be happy to contribute back.

**Comment by burakcan** [comment]
Great @leesalminen :) Thanks :+1:

**Comment by burakcan** [comment]
@leesalminen did you have any progress on this?

**Comment by leesalminen** [comment]
Work in progress here: https://github.com/lofiinterstate/react-date-range/

**Comment by supersky07** [comment]
@leesalminen Look forward to this！

**Comment by burakcan** [comment]
https://github.com/Adphorus/react-date-range/issues/37
