### ISSUE TITLE
How to Hide the bottom part of DefinedRange?

### ISSUE THREAD

**Issue by HashemDeveloper** [hypeserver/react-date-range#404]
Hide the bottom part of DefinedRange?
![reactdaterange1](https://user-images.githubusercontent.com/42665240/91593084-86a54680-e92d-11ea-9e4b-15fed3ae13a5.jpg)

I was wonder if there's a way to hide the bottom part. Really appreciate your help. Thank you.

**Comment by guruji123** [comment]
I am also looking for this solution.

**Comment by HashemDeveloper** [comment]
@guruji123 Had no choice but to use different library!

**Comment by Jawadgee** [comment]
You could have hide with css

**Comment by Jawadgee** [comment]
> @guruji123 Had no choice but to use different library!

You could have hide with css

**Comment by chrisclausen90** [comment]
Use this

inputRanges={[]}
