### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by ao-alex** [hypeserver/react-date-range#409]
Is this maintained?

**Comment by yigitbey** [comment]
Hello,

We've moved this repository to a new github organization (Adphorus -> Hypeserver). All the original maintainers (@burakcan, @mkg0 and @onurkerimov) are onboard again. I guess they will go over the list of issues and PR's soon.

**Comment by burakcan** [comment]
Hi @ao-alex,
It is maintained but we are not actively working on improving it. It is relatively stable at this point with not too many bugs and has enough features to do what it promises to.

Regarding the current prs and issues:
The repo and the library went through a change of ownership recently; it is now maintained by individuals (original devs) and is not backed by a company. We will probably go through the list of prs and issues soon to resolve as much as we can.
