### ISSUE TITLE
how to change the locale?

### ISSUE THREAD

**Issue by fydsa** [hypeserver/react-date-range#412]
Hi,

I need to change the locale using this library. I changed the locale object in the props and the value of its "code" key to something other than enUS" but nothing changed. Is there any other parameter that needs to be changed? I really appreciate any help.

**Comment by flobrflo** [comment]
Hello,
I just do the locale update for my side : 

const locale = require(`date-fns/locale/$myCustomLang/index.js`);

then use like that :
<DateRangePicker
    ...
    locale={locale}
/>
