### ISSUE TITLE
Release 1.0 

### ISSUE THREAD

**Issue by burakcan** [hypeserver/react-date-range#42]
I think the library itself is in an enough condition to release 1.0. But before doing so; we need to complete and organize the documentation. @strada @fatiherikli mayday :)

**Comment by aweber1** [comment]
Quick question, any chance you could publish the current library to npm as maybe 0.2.3 release? Cheers!

**Comment by burakcan** [comment]
@aweber1 
<img width="187" alt="screen shot 2016-02-18 at 16 14 56" src="https://cloud.githubusercontent.com/assets/3121257/13145665/da6dc39a-d65a-11e5-9fb3-5e52b5ea8c76.png">
:)

**Comment by aweber1** [comment]
awesome, thanks!

**Comment by hassankhan** [comment]
Hi! Love your library, thanks for writing it! I thought I'd just add my 2c, I'd prefer if the v1 release had some sort of unit testing (#24) just for reliabilty's sake.

**Comment by jacobrask** [comment]
I am willing to help. I understand (and have experience with) the work load of maintaining an open source project, so if you want some relief I would also be willing to be a collaborator and perhaps even add a small test suite.
