### ISSUE TITLE
Request: Add option where selecting a date in-view doesn't cause a focus change

### ISSUE THREAD

**Issue by lexispike** [hypeserver/react-date-range#427]
## Subject of the issue

I'm using the `DateRangePicker` with 2 months showing with the horizontal display. When I select a date showing on the right calendar, the selection causes an auto-focus so that the selected date is now shown on the left calendar. With my use case, the user cannot select any date after today, so this behavior creates a weird experience when I select `Today` for example (where the right calendar is completely disabled). 

Alternatively, if [this issue](https://github.com/hypeserver/react-date-range/issues/268) was fixed, I think that would fix my base issue here, but I still think having this as an option would be net-positive.

## Environment
Package Version: 1.1.3
React version: 16.8.6
Node version: 8.17.0
Browser: Chrome 85.0.4183.121

**Comment by Wgil** [comment]
I'd also like this be implemented

**Comment by Wgil** [comment]
Is there any chance a maintainer could consider including this functionality? There's a pull request created already

**Comment by ginnerzapata** [comment]
This functionality would be amazing to have

**Comment by Skorpioh** [comment]
We desperately need this. The current behavior is a disaster, the calendar is flipped under the user's cursor without them moving the mouse basically preselecting/highlighting a 1 month period without them actively interacting with the multi-month calendar. Super confusing.

**Comment by teksebarna** [comment]
Too bad I haven't found this issue earlier, so I wouldn't have to create [a new one](https://github.com/hypeserver/react-date-range/issues/441).
But I'm still facing the same problem and I would really appreciate it we could have this fix implemented as soon as possible.
Thank you!

**Comment by dashdanilo** [comment]
I have the same problem implementing it in the vertical scroll, when I click next month it jumps to the selected month making the user experience strange. Any solution for that?

**Comment by kamyar** [comment]
Sorry for the late reply.
This is indeed an issue that is annoying.
Please let me know what you think about https://github.com/hypeserver/react-date-range/pull/428 and we can try to include that in the next release.

**Comment by peterschwarzdev** [comment]
Any chance to get the #428  reviewed? Seems like is ready to be merged.

**Comment by kamyar** [comment]
Fixed in 1.4.0
