### ISSUE TITLE
How can I change the color of underline below today's day in calendar?

### ISSUE THREAD

**Issue by lev1rand** [hypeserver/react-date-range#442]
For example, I wanna replace blue color with black color. How can I do it? As I saw, this blue color is hardcoded in css.
So what should I do?

![image](https://user-images.githubusercontent.com/60857659/106861190-1c5bb380-66ce-11eb-89ee-ad0571694d8f.png)

**Comment by felipeloha** [comment]
.rdrDayToday .rdrDayNumber span:after {
    background: $date-picker-selection-color;
  }

**Comment by kamyar** [comment]
We recently added `dayContentRenderer` prop also, there is a new demo for showing an orange dot if a date is a weekend for example.
https://hypeserver.github.io/react-date-range/
You can achieve this also with a similar approach. :)
