### ISSUE TITLE
Year and Days of Week not showing correctly after update

### ISSUE THREAD

**Issue by wvpioneers** [hypeserver/react-date-range#481]
## Subject of the issue
Year and Days of Week not showing correctly after update
 
## [BUG] Bug Reproduce Steps

- Updated package from 1.1.3 to 1.1.4
  - year displays as yyyy on input fields
  - days of week shows 0 - 6 (0 = sunday, 6 = saturday) on calendar
- removed component and used DateRange example
- issue still persist

![Capture](https://user-images.githubusercontent.com/71338026/120487488-ddcbc200-c36a-11eb-8525-1c7a52593b00.PNG)

## [BUG] Expected behaviour

- Days of week to show on calendar, year to show in input

## Environment
Package Version: 1.1.4
React version: 16.13.1
Node version: 14.15.0
Browser: chrome

**Comment by kamyar** [comment]
Thanks for the report, can you re/confirm just updating the version back to 1.1.3 fixes the issue?
Also can you share how the component is being called?

**Comment by kamyar** [comment]
actually if a jsfiddle or similar online "working" version would be much appreciated if you can provide and would reduce our time to fix the bug.

**Comment by wvpioneers** [comment]
ah, I can't replicate it outside my project. I may need to just start with a fresh component again

**Comment by wvpioneers** [comment]
https://codesandbox.io/s/daterangeissue-e4j9e?file=/src/dateRangeSelector.tsx

**Comment by wvpioneers** [comment]
I nuked my node_module folder and automagically works! sorry, should've known better. Thanks for reaching out.

**Comment by kamyar** [comment]
@wvpioneers Great to hear that!
I will close the issue then! :)
