### ISSUE TITLE
DefinedRange type issue 

### ISSUE THREAD

**Issue by nriin-oji** [hypeserver/react-date-range#493]
## Subject of the issue
`'DefinedRange' only refers to a type, but is being used as a value here.` 
Although this issue exists, it does not break the code. yet it trigger the linter.
My temporary solution is duplicate existing types then re-create on new global.d.ts file

> **My implementation**

![Screenshot_48](https://user-images.githubusercontent.com/53163902/122000925-c6182300-cdd9-11eb-8aaf-d3fc6b018a00.png)

> **Defined range exported type instead of class**

![Screenshot_49](https://user-images.githubusercontent.com/53163902/122000937-ca444080-cdd9-11eb-85c1-01f7170ebc96.png)
 
## [BUG] Bug Reproduce Steps
I just following the instruction based on this [page](https://hypeserver.github.io/react-date-range/#definedrange) 

## [BUG] Expected behaviour
Import the DefinedRange without issue

## Environment
Package Version: 1.2.0
React version: 16.12.0
Typescript version: 4.2.4
Node version: 12.0.0
Browser:  Chrome 91.0.4472.101

**Comment by kamyar** [comment]
Where do you use the types from?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-date-range/index.d.ts#L289 ?
Because that one is outdated as far as I know

**Comment by nriin-oji** [comment]
@kamyar I was using that one

**Comment by naufaldi** [comment]
any update regarding this @kamyar @nriin-oji  ?  i have same problem.

**Comment by nriin-oji** [comment]
> any update regarding this @kamyar @nriin-oji ? i have same problem.

I copied original type then create new type in global.d.ts and adjust the DefinedRange type to
`  export class DefinedRange extends React.Component<DefinedRangeProps> {}
`
