### ISSUE TITLE
How to create and add a custom defined range to the list of defined range already present 

### ISSUE THREAD

**Issue by AdityaKallur** [hypeserver/react-date-range#507]
I have to add a defined range of past 12months date range to the already existing list of defined ranges 

![image](https://user-images.githubusercontent.com/83698184/128137571-5457ead6-63d2-47e2-b0e5-1ef7c3d451d2.png)

**Comment by AdityaKallur** [comment]
I got the solution for this

**Comment by keyurparalkar** [comment]
@AdityaKallur Can you please tell me how you achieved it? I have the same requirement

**Comment by AdityaKallur** [comment]
@keyurparalkar 

import {defaultStaticRanges} from "react-date-range"; // this will give you already defined list
import { createStaticRanges } from "react-date-range"; //pass your object to this method

let myValue= {
    label: 'My Defined Range',             // this is your predefined date range object
    range: () => ({
        startDate: <pass the start date>,
        endDate: <pass the end date>
    }),
};

let yourDateRange= createStaticRanges([myValue]);

<DateRangePicker
          className={"DateRangeWrapper"}
          ranges={[selectionRange]}
          onChange={this.handleDateRangeSelect}
          showSelectionPreview={true}
          moveRangeOnFirstSelection={false}
          direction="horizontal"
          staticRanges = {[...defaultStaticRanges, ...yourDateRange]} //combine to one array and pass it here
          maxDate={new Date()}
></DateRangePicker>

**Comment by atefBB** [comment]
@AdityaKallur you saved my day ! Thank you !
