### ISSUE TITLE
TypeError: (0 , _addYears.default) is not a function in React Date Range while using in Next Js

### ISSUE THREAD

**Issue by muhammadfaizan027915** [hypeserver/react-date-range#630]
## Subject of the issue
While using a React Date Range in Next Js getting an issue, "TypeError: (0 , _addYears.default) is not a function". 

Code for using a calender from react date range.
/app/page.tsx
```
"use client";

import { Calendar } from "react-date-range";

export default function Home() {
  function handleSelect(date: Date) {
    console.log(date); // native Date object
  }
  return <Calendar date={new Date()} onChange={handleSelect} />;
}

```
The Error that I am getting on my browser is:
![Screenshot_1](https://github.com/hypeserver/react-date-range/assets/55981656/219b3c66-05f2-4614-ad6a-30d1934fa5d0)

Installed Dependencies are: 
{
  "name": "date-range-picker",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "date-fns": "^3.0.4",
    "next": "14.0.4",
    "react": "^18.2.0",
    "react-date-range": "^1.4.0",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-date-range": "^1.4.9",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.0.4",
    "typescript": "^5"
  }
}

 
## [BUG] Bug Reproduce Steps
Just create a Next Js project and install the react date range, And use in Next Js Application to produce an error.
Reference Repository contains code with given error: 
https://github.com/muhammadfaizan027915/react-date-range-bug.git

/app/page.tsx
```
"use client";

import { Calendar } from "react-date-range";

export default function Home() {
  function handleSelect(date: Date) {
    console.log(date); // native Date object
  }
  return <Calendar date={new Date()} onChange={handleSelect} />;
}

```
## [BUG] Expected behaviour
Expected behaviour is that Calender must be rendered in a next js project and can be used.

## Environment
Package Version: "^1.4.0"
React version: 18.2.0
Node version: 20.9.0
Browser: Chrome, Safari, Edge, Firefox

**Comment by alaacoffeeit** [comment]
:(

**Comment by muhammadfaizan027915** [comment]
> :(

I'm facing this issue, is there any way to resolve this issue ?

**Comment by tkanemoto** [comment]
_addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`

**Comment by muhammadfaizan027915** [comment]
> _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`

I had installed date-fns@3.0.0 as a dependency for react date range.

**Comment by gabscar** [comment]
> > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> 
> I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.

try with  2.30.0, it worked here

**Comment by rmosias2** [comment]
same here ``Uncaught TypeError: (0 , _addYears.default) is not a function
    at ../../node_modules/.pnpm/react-date-range@1.4.0_date-fns@3.0.0_react@18.2.0/node_modules/react-date-range/dist/components/Calendar/index.js``

**Comment by muhammadfaizan027915** [comment]
> > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > 
> > 
> > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> 
> try with 2.30.0, it worked here

I had tried lower versions till 2.0.0 but hadn't worked.

**Comment by Aakashgupta2001** [comment]
> > > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > > 
> > > 
> > > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> > 
> > 
> > try with 2.30.0, it worked here
> 
> I had tried lower versions till 2.0.0 but hadn't worked.

install version 2.30.0, then delete your node modules, install it again and it is working for me.

**Comment by tkanemoto** [comment]
I said `date-fns@<3.0.0` not `date-fns@3.0.0`.

**Comment by umakantp** [comment]
Okay, I wanted to use the latest `date-fns` and this package was not compatible. I forked this repo and changed it to work with the latest `date-fns`. In case you want to use it: https://www.npmjs.com/package/@umakantp/react-date-range

**Comment by behroozaone** [comment]
> Okay, I wanted to use the latest `date-fns` and this package was not compatible. I forked this repo and changed it to work with the latest `date-fns`. In case you want to use it: https://www.npmjs.com/package/@umakantp/react-date-range

 try this way it worked for me

**Comment by tutusjr** [comment]
installing version date-fns@2.30.0 worked for me

**Comment by keremciu** [comment]
I prepare a new version with a compability of date-fns@3.x.x

**Comment by keremciu** [comment]
@muhammadfaizan027915 @tutusjr @behroozaone @umakantp @tkanemoto @Aakashgupta2001 @gabscar @rmosias2 @alaacoffeeit

can you please try latest version? https://www.npmjs.com/package/react-date-range/v/2.0.0-alpha.3 that should be working with date-fns@3

**Comment by muhammadfaizan027915** [comment]
> @muhammadfaizan027915 @tutusjr @behroozaone @umakantp @tkanemoto @Aakashgupta2001 @gabscar @rmosias2 @alaacoffeeit
> 
> can you please try latest version? https://www.npmjs.com/package/react-date-range/v/2.0.0-alpha.3 that should be working with date-fns@3

Thanks for creating a newer version of date range picker compatible with date-fns@3.0.0. It has solved all the issues that I was facing, thanks once again.

**Comment by muhammadfaizan027915** [comment]
> @muhammadfaizan027915 @tutusjr @behroozaone @umakantp @tkanemoto @Aakashgupta2001 @gabscar @rmosias2 @alaacoffeeit
> 
> can you please try latest version? https://www.npmjs.com/package/react-date-range/v/2.0.0-alpha.3 that should be working with date-fns@3

Thanks for creating a newer version of date range picker compatible with date-fns@3.0.0. It has solved all the issues that I was facing, thanks once again.

**Comment by behroozaone** [comment]
@umakantp/react-date-range": "^2.1.0",

**Comment by behroozaone** [comment]
"date-fns": "^3.0.6",

**Comment by rcrafael** [comment]
> > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > 
> > 
> > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> 
> try with 2.30.0, it worked here

this really works for me. 
react-date-range@1.4.0
date-fns@2.30.0

thanks!

**Comment by jibon0070** [comment]
> > > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > > 
> > > 
> > > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> > 
> > 
> > try with 2.30.0, it worked here
> 
> this really works for me. react-date-range@1.4.0 date-fns@2.30.0
> 
> thanks!

thanks this helped

**Comment by emmanuelokorie1** [comment]
i have tried almost everything here, 
it still didnt work for me

**Comment by emmanuelokorie1** [comment]
> > > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > > 
> > > 
> > > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> > 
> > 
> > try with 2.30.0, it worked here
> 
> this really works for me. react-date-range@1.4.0 date-fns@2.30.0
> 
> thanks!

thanks 
this worked

**Comment by Aumkar010** [comment]
> > > > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > > > 
> > > > 
> > > > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> > > 
> > > 
> > > try with 2.30.0, it worked here
> > 
> > 
> > I had tried lower versions till 2.0.0 but hadn't worked.
> 
> install version 2.30.0, then delete your node modules, install it again and it is working for me.

thank you so much my the god bless you and fulfil all your desires

**Comment by Gurkirat27GK** [comment]
> > > > _addYears is imported from date-fns. date-fns 3.0.0. has been released recently. You can work around this by installing `date-fns@<3.0.0`
> > > 
> > > 
> > > I had installed date-fns@3.0.0 as a dependency for react date range, but it had not worked.
> > 
> > 
> > try with 2.30.0, it worked here
> 
> this really works for me. react-date-range@1.4.0 date-fns@2.30.0
> 
> thanks!
But this didn't worked for me. Can anyone help??

**Comment by muhammadfaizan027915** [comment]
> @muhammadfaizan027915 @tutusjr @behroozaone @umakantp @tkanemoto @Aakashgupta2001 @gabscar @rmosias2 @alaacoffeeit
> 
> can you please try latest version? https://www.npmjs.com/package/react-date-range/v/2.0.0-alpha.3 that should be working with date-fns@3

@umakantp Try to use latest version of date range.

**Comment by WassimBelhadjRhouma** [comment]
You have to determine and find which versions work together. For example react-date-range  version 1.4.0  and date-fns 2.28.0.

  => npm install react-date-range@1.4.0 date-fns@2.28.0
If this didn't work, check your package.json file and confirm these given version are changed. otherwise, delete them manually from the package.json, replace with: 
   => "react-date-range": "1.4.0",
    "date-fns": "2.28.0"
and then => npm install

hope this resolve the issue.
