### ISSUE TITLE
Is there any option to hide the navigation?

### ISSUE THREAD

**Issue by kevin1193** [hypeserver/react-date-range#635]
## Subject of the issue
Option to hide the left side navigation and options.

<img width="262" alt="image" src="https://github.com/hypeserver/react-date-range/assets/4178188/d3325218-e917-4c3d-afe4-f04b2aae8f10">

**Comment by keremciu** [comment]
if you look at the daterangepicker component code, you can see that the part you called is 'DefinedRange' component, basically if you use only daterange, you get what you want.

as this demo shows: https://hypeserver.github.io/react-date-range/#daterange
