### ISSUE TITLE
v1.4.0 gives an issue date-fns/max module not found. i have used v1.4.0 in production. 

### ISSUE THREAD

**Issue by abdarker** [hypeserver/react-date-range#638]
## Subject of the issue
1.4.0 gives an issue date-fns/max module not found. i have used v1.4.0 in production. now what should i do for a long term solution.
 
## [BUG] Bug Reproduce Steps
1.4.0 gives an issue date-fns/max module not found. i have used v1.4.0 in production. now what should i do for a long term solution.

## [BUG] Expected behaviour
1.4.0 gives an issue date-fns/max module not found. i have used v1.4.0 in production. now what should i do for a long term solution.

## Environment
Package Version: v1.4.0
React version: 18.2.0
Node version: 18
Browser: chrome
![image](https://github.com/hypeserver/react-date-range/assets/14371506/98d0251d-1acc-47bd-8304-e487eb3d092a)

**Comment by Dev-Sharma-197** [comment]
have you found any solution?

**Comment by abdarker** [comment]
yes i have. all you need to do is putting these two lines in dependencies in package.json if you are using v1.4.0 and do a clean install your node module that should fix your problem.

 "react-date-range": "1.4.0",
  "date-fns": "2.0.0-alpha.7 || >=2.0.0",
