### ISSUE TITLE
Why am not I a contributor?

### ISSUE THREAD

**Issue by ParadeTo** [hypeserver/react-date-range#84]
I committed code. But why am not I a contributor?

**Comment by burakcan** [comment]
Hi @ParadeTo . I merged some of the prs manually because of the conflicts. I think that caused this problem. If you want, we can revert the changes and have them applied after solving the conflicts. This won't require a version bump, just a commit reorganisation.

**Comment by ParadeTo** [comment]
Ok. I really appreciate the effort you will make.
